### ISSUE TITLE
The cursor is not visible in the web version.

### ISSUE THREAD

**Issue by Adembc** [MohamedRejeb/Compose-Rich-Editor#10]
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/71262172/235675762-e5bd97ab-0a33-4e82-9666-5caed06a7a09.png">

**Comment by MohamedRejeb** [comment]
I've create an issue in compose multiplatform project: https://github.com/JetBrains/compose-multiplatform/issues/3120

**Comment by MohamedRejeb** [comment]
I'm going to close this issue since it's not related to the library itself.
