### ISSUE TITLE
Keyboard should not display in RichTextEditor when readOnly=true

### ISSUE THREAD

**Issue by brendanw** [MohamedRejeb/Compose-Rich-Editor#100]
I am using the RichTextEditor for the purpose of rendering text that has embedded html. When creating a RichTextEditor where `readOnly=true` and selecting that text, the keyboard pops up. I'd expect the keyboard to not pop up from any interaction with a RichTextEditor where `readOnly=true`

**Comment by MohamedRejeb** [comment]
For that case it's better to use `RichText` instead of `RichTextEditor`
