### ISSUE TITLE
dependency name is incorrect

### ISSUE THREAD

**Issue by karan-ta** [MohamedRejeb/Compose-Rich-Editor#123]
implementation("com.mohamedrejeb.richeditor:richeditor-compose:1.0.0-beta03") mentioned in readme
and
https://mvnrepository.com/artifact/com.mohamedrejeb.richeditor/richeditor-compose-desktop

have different names.

**Comment by MohamedRejeb** [comment]
It's correct, that one if just for desktop target. That howa kotlin multiplatform works, there's also richeditor-compose-android and same for other targets.

Check these
https://mvnrepository.com/artifact/com.mohamedrejeb.richeditor/richeditor-compose
https://mvnrepository.com/artifact/com.mohamedrejeb.richeditor

**Comment by MohamedRejeb** [comment]
In Gradle you only need the one mentioned in readme richeditor-compose
