### ISSUE TITLE
Not able to get data from editor which we used options

### ISSUE THREAD

**Issue by MahendranGovindarajan** [MohamedRejeb/Compose-Rich-Editor#124]
Team I need sample for get data from Editor as what ever used formats like Bold or Italic, etc... Not able to restrict length. Help me on this. How to get editor data and limit the maximum character

**Comment by MohamedRejeb** [comment]
Hi,
You can use `richTextState.currentSpanStyle` to get the current span style and then use `val isBold = currentSpanStyle.fontWeight = FontWeight.Bold ` to know if it is bold or not, for example.

https://mohamedrejeb.github.io/Compose-Rich-Editor/span_style/#styling-spans

For now there's no way to set a character limit. That's important I'll try to implement it ASAP

**Comment by MahendranGovindarajan** [comment]
But I need to get data from Editor with bold and whatever I used in outline text field. I need to POST that data to server. I cant  find any samples for this... Just give me an Idea for this

**Comment by MohamedRejeb** [comment]
I'm not sure if I understand correctly, for saving data to server we support HTML. So you can transfer your RichTextState into HTML string that could be saved to the server, and you transfer it back to RichTextState later.

Check this [link](https://mohamedrejeb.github.io/Compose-Rich-Editor/html_import_export/)

**Comment by MahendranGovindarajan** [comment]
Hey, Mohamed Thanks for your reply. I can access now. Thanks for your prompt response

**Comment by MahendranGovindarajan** [comment]
.
