### ISSUE TITLE
How to integrate rich text editor as only view and getting data in SwiftUI app - iOS

### ISSUE THREAD

**Issue by hardik-frontline** [MohamedRejeb/Compose-Rich-Editor#125]
Hello, 

I am trying to integrate a rich text editor in the SwiftUI app, but it is returning as UIViewController not View.

Below is the code:

`                ComposeViewControllerToSwiftUI(
                    topSafeArea: Float(geo.safeAreaInsets.top),
                    bottomSafeArea: Float(geo.safeAreaInsets.bottom)
                )
                .ignoresSafeArea()
`

`
import SwiftUI
import common

struct ComposeViewControllerToSwiftUI: UIViewControllerRepresentable {
    private let topSafeArea: Float
    private let bottomSafeArea: Float
    
    init(topSafeArea: Float, bottomSafeArea: Float) {
        self.topSafeArea = topSafeArea
        self.bottomSafeArea = bottomSafeArea
    }
    
    func makeUIViewController(context: Context) -> UIViewController {
       return Main_iosKt.MainViewController(
            topSafeArea: topSafeArea,
            bottomSafeArea: bottomSafeArea
        )
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {
    }    
}
`
How can I get only a rich text editor view to add inside other views and access the HTML data from an editor?

**Comment by MohamedRejeb** [comment]
I didn't try something like this, and I think that it's it is not going to work correctly. This rich editor is made to be used from Compose code not SwiftUI. But you can try this approach and see if it works, what you need to do it to call that `UIViewController` from your SwiftUI code as a View.
https://sarunw.com/posts/uiviewcontroller-in-swiftui/

**Comment by hardik-frontline** [comment]
Okay, but how can I access data in the iOS app? 

`func makeUIViewController(context: Context) -> UIViewController {
   return Main_iosKt.MainViewController(
        topSafeArea: topSafeArea,
        bottomSafeArea: bottomSafeArea
    )
}
`

Currently, we are creating a view controller using the above code and we are using the below function to access above main controller.

`@Suppress("unused", "FunctionName")
fun MainViewController(
    topSafeArea: Float,
    bottomSafeArea: Float
): UIViewController {
    return ComposeUIViewController {
        Box(
            modifier = Modifier
                .fillMaxSize()
        ) {
            App()
        }
    }
}
`

So, how can I fetch data in this main controller from Kotlin code? 

Or do I need to implement everything in Kotlin and just need to add view controller logic to display in iOS.

**Comment by MohamedRejeb** [comment]
The library is made mainly for Compose, I didn't try using it in a UiKit project.
