### ISSUE TITLE
Does it make sense providing a simple `Text`/`ClickableText` like component for rendering markdown/html static content?

### ISSUE THREAD

**Issue by mr3y-the-programmer** [MohamedRejeb/Compose-Rich-Editor#128]
Use case is to have a composable that can render/display RSS feed content or just a part of it as a summary, for example like this:
![Capture](https://github.com/MohamedRejeb/Compose-Rich-Editor/assets/26522145/94ea7e81-fb13-4c0c-aaf7-7796378ddfc4)
As you can see, the text "Welcome to the latest edition of......etc" is rendered by a composable that is able to parse the HTML tags and convert those to equivalent `AnnotatedString` spans, and render that accordingly. it also allows the caller to pass some parameters (`maxLines`, `overflow`...etc) similar to what he would pass to normal `Text` Composable to control the text appearance.

I know I can do something similar using the current APIs provided by the library, but I've found some non-negligible drawbacks. First of all, the API seems like an overkill for this simple case as it is designed specifically for editing & interacting with the content, Second, in order to get the overflow '...' behaviour for example, I would need to customize `onTextLayout` parameter to update the text based on lineCount, and this, unfortunately, would cost 1 additional frame to see the end result.

That being said, I'm asking if a simple alternative API would make sense to add to the library? or is this something that is out of the scope of the project? 

I would probably build it using the underlying `KSoup` to parse the HTML tags and provide a wrapper around built-in composable like `Text`.

**Comment by MohamedRejeb** [comment]
This API is already available, you can use `RichText` Composable.

**Comment by mr3y-the-programmer** [comment]
After using this API in a side project, I can't build the app successfully, it always fails with an error message like this:
```
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     com.mr3y.ludi.app-mergeDebugResources-4:/values/values.xml:480: error: style attribute 'attr/colorPrimary (aka com.mr3y.ludi:attr/colorPrimary)' not found.
     com.mr3y.ludi.app-mergeDebugResources-4:/values/values.xml:481: error: style attribute 'attr/colorOnPrimary (aka com.mr3y.ludi:attr/colorOnPrimary)' not found.
     com.mr3y.ludi.app-mergeDebugResources-4:/values/values.xml:482: error: style attribute 'attr/colorSecondary (aka com.mr3y.ludi:attr/colorSecondary)' not found.
     com.mr3y.ludi.app-mergeDebugResources-4:/values/values.xml:483: error: style attribute 'attr/colorOnSecondary (aka com.mr3y.ludi:attr/colorOnSecondary)' not found.
     com.mr3y.ludi.app-mergeDebugResources-4:/values/values.xml:485: error: style attribute 'attr/colorOnBackground (aka com.mr3y.ludi:attr/colorOnBackground)' not found.
     com.mr3y.ludi.app-mergeDebugResources-4:/values-night-v8/values-night-v8.xml:8: error: style attribute 'attr/colorPrimary (aka com.mr3y.ludi:attr/colorPrimary)' not found.
     com.mr3y.ludi.app-mergeDebugResources-4:/values-night-v8/values-night-v8.xml:9: error: style attribute 'attr/colorOnPrimary (aka com.mr3y.ludi:attr/colorOnPrimary)' not found.
     com.mr3y.ludi.app-mergeDebugResources-4:/values-night-v8/values-night-v8.xml:10: error: style attribute 'attr/colorSecondary (aka com.mr3y.ludi:attr/colorSecondary)' not found.
     com.mr3y.ludi.app-mergeDebugResources-4:/values-night-v8/values-night-v8.xml:11: error: style attribute 'attr/colorOnSecondary (aka com.mr3y.ludi:attr/colorOnSecondary)' not found.
     com.mr3y.ludi.app-mergeDebugResources-4:/values-night-v8/values-night-v8.xml:13: error: style attribute 'attr/colorOnBackground (aka com.mr3y.ludi:attr/colorOnBackground)' not found.
     error: failed linking references.
```
the build fails on both locally & CI, I'll open a new issue with more details.
