### ISSUE TITLE
Support for Compose Multiplatform v1.5.10 and Kotlin 1.9.20

### ISSUE THREAD

**Issue by Vaibhav2002** [MohamedRejeb/Compose-Rich-Editor#136]
This library is not compatible with Compose Multiplatform v1.5.10
As soon as I add the dependencies, I cant access anything which was added in Compose 1.5.10, for example `ExposedDropDownMenu` and any other Compose 1.5.10 will not work.

**Comment by MohamedRejeb** [comment]
Fixed in #137
