### ISSUE TITLE
Support limiting characters in TextField

### ISSUE THREAD

**Issue by Vaibhav2002** [MohamedRejeb/Compose-Rich-Editor#143]
Suppose we have a feature in which we want to allow users to input up to X amount of characters, there is no way to achieve this now as state is handled internally.

**Comment by Vaibhav2002** [comment]
Can you assign this to me?

**Comment by MohamedRejeb** [comment]
Yes sure,
Feel free to ask any questions you may have. You can use the `updateTextFieldValue` and `onTextFieldValueChange` methods in `RichTextState` to add this validation. You can use `newTextFieldValue.text` to get the number of characters of the new typed string.
