### ISSUE TITLE
setHtml ignore fontSize

### ISSUE THREAD

**Issue by Alexyvercruysse** [MohamedRejeb/Compose-Rich-Editor#152]
Hello,
I'm trying to insert html into BasicRichTextEditor, but once the html is inserted it ignore fontSize. 
Here is my BasicRichTextEditor : 
`
BasicRichTextEditor(
    state = state,
    textStyle = TextStyle(
        fontFamily = camptonFontFamily,
        fontWeight = FontWeight.Normal,
        fontStyle = FontStyle.Normal,
        fontSize = TextUnit(25F, TextUnitType.Sp)
    )
)
`

The issue persist with setText too. 
All other parameters work correctly.

**Comment by MohamedRejeb** [comment]
Hello,
Thanks for reporting this issue. It's going to be fixed in the next release (mostly this week).

**Comment by Alexyvercruysse** [comment]
Okay, thank you! 
Congratulations on your work
