### ISSUE TITLE
Not all HTML char escapes are converted

### ISSUE THREAD

**Issue by garretyoder** [MohamedRejeb/Compose-Rich-Editor#157]
Some direct char codes like `&quot` are escaped and converted into " properly, however html style `&#x27;` are not converted properly.

Example of how I'm using it:

```kotlin
val richTextState = rememberRichTextState()
LaunchedEffect(string) {
    richTextState.setHtml(string)
}
RichText(
    state = richTextState,
    modifier = Modifier
)
```

**Comment by garretyoder** [comment]
I have a workaround for the time being using regex to pull out the unicode codepoint, and convert it into an int and then back to a character. Is there something I'm missing where this should be done automatically?

`text.replace(regex = Regex("&#x([^;]*);")) {
    "${it.groupValues[1].toInt(16).toChar()}"
}`

**Comment by MohamedRejeb** [comment]
Thanks for reporting this issue. I will check it out.

**Comment by MohamedRejeb** [comment]
It will be available in the next release.
