### ISSUE TITLE
Pressing enter after typing in list

### ISSUE THREAD

**Issue by Utkarsh831** [MohamedRejeb/Compose-Rich-Editor#160]
On the web, whenever I press enter after typing in a list, the list gets untoggled and we have to toggle it again. Do we have any workaround for this?
<img width="746" alt="Screenshot 2023-12-28 at 2 07 18 PM" src="https://github.com/MohamedRejeb/Compose-Rich-Editor/assets/92424321/5288fbb3-3681-48b4-a425-7b68b1c9f676">

**Comment by MohamedRejeb** [comment]
Thanks for reporting this issue. It should be the same as other targets. I will work on it.
