### ISSUE TITLE
Readme is bad

### ISSUE THREAD

**Issue by the-best-is-best** [MohamedRejeb/compose-rich-editor#177]
Why don't make full code with all features in this package and how use it and where the tool bar ?

**Comment by MohamedRejeb** [comment]
Thanks for your feedback, I will try to make things clearer.
This Slack demo here contains most of the library features: https://github.com/MohamedRejeb/Compose-Rich-Editor/tree/main/sample/common/src/commonMain/kotlin/com/mohamedrejeb/richeditor/sample/common/slack

**Comment by MohamedRejeb** [comment]
There's a detailed description of each public API as well as some good demos that you can check. I think this is more than enough, please let me know if you still think that there's something missing.

Docs: https://mohamedrejeb.github.io/compose-rich-editor/
Samples: [Slack Demo](https://github.com/MohamedRejeb/compose-rich-editor/tree/main/sample/common/src/commonMain/kotlin/com/mohamedrejeb/richeditor/sample/common/slack)
