### ISSUE TITLE
Not able to write new text when i use setHtml(), setMarkdown() or setText() to set initial text.

### ISSUE THREAD

**Issue by saaric** [MohamedRejeb/Compose-Rich-Editor#180]
If I use state.setMarkdown() or state.setHtml() or setText() I am not able to edit the text in RichTextEditor.

**Comment by MohamedRejeb** [comment]
Can you share a sample of your code? Because it's working fine for me

**Comment by jaks6** [comment]
Hi, I am experiencing the same issue:

```
@Composable
fun Editor(text:String, modifier: Modifier)
{
    val state = rememberRichTextState()

    state.setText(text)

    BasicRichTextEditor(
        state = state,
        modifier = modifier
    )

}


With setText(..), I can click on the text field and the keyboard appears, but entering input does not change what is visible. I tested on API 30 emulator, compileSdk = 34, minSdk = 24,  targetSdk = 34
```

**Comment by MohamedRejeb** [comment]
Thanks!
I will check it out.

**Comment by Narutohach** [comment]
I solved this problem like this: 
` var action = false
fun setHtml(html: String) {
        val richParagraphList = RichTextStateHtmlParser.encode(html).richParagraphList
        if (!action) {
            updateRichParagraphList(richParagraphList)
            action = true
        }
    }`

**Comment by MohamedRejeb** [comment]
In Compose try to avoid calling normal functions inside a Composable function. You need to call setText, setHtml, setMarkdown... from a non Compose context such as a LaunchedEffect. That's why you were having this problem.
