### ISSUE TITLE
Use <strong> tag for Bold text instead of CSS font-weight

### ISSUE THREAD

**Issue by GimazDo** [MohamedRejeb/Compose-Rich-Editor#188]
Hello,

I've been using your library and I noticed that it uses the CSS attribute `font-weight` for rendering bold text. While this approach is functional, I wanted to suggest considering the use of the HTML `<strong>` tag instead.

**Comment by MohamedRejeb** [comment]
Hi,
Thanks for your feedback. I will consider adding this optimization in future releases.
