### ISSUE TITLE
How to display buttons?

### ISSUE THREAD

**Issue by SanEffect** [MohamedRejeb/Compose-Rich-Editor#189]
Hello.
It is probably incorrect to create a question in "issues", but from your documentation it is completely unclear how to display the buttons. Is this even possible or should each developer add them themselves and tie them to the functionality? I don’t see the buttons from a typical wysiwyg editor: bold, italic, underline and all the others.
Maybe I'm doing something wrong?

**Comment by Efimj** [comment]
I had the same question, I made my own components, you can look and play with:

[RichTextStyleButton](https://github.com/Efimj/Shkiper/blob/master/app/src/main/java/com/jobik/shkiper/ui/components/buttons/RichTextStyleButton.kt)
[RichTextBottomToolBar](https://github.com/Efimj/Shkiper/blob/master/app/src/main/java/com/jobik/shkiper/ui/components/layouts/RichTextBottomToolBar.kt)
[RichTextHeaderToolBar](https://github.com/Efimj/Shkiper/blob/master/app/src/main/java/com/jobik/shkiper/ui/components/layouts/RichTextHeaderToolBar.kt)

it looks like this:
![image](https://github.com/MohamedRejeb/Compose-Rich-Editor/assets/87390257/208d6ce4-b366-4796-94ea-a9dd669f73aa)

Also, this question has already been asked, it became a prototype for my implementation:
[Issue](https://github.com/MohamedRejeb/Compose-Rich-Editor/issues/43)

**Comment by MohamedRejeb** [comment]
Hi,
You need to create the buttons by yourself. You can use the sample a reference [here](https://github.com/MohamedRejeb/Compose-Rich-Editor/blob/main/sample/common/src/commonMain/kotlin/com/mohamedrejeb/richeditor/sample/common/components/RichTextStyleRow.kt)

I take the decision to provide the necessary public APIs so you can create your own custom control buttons, which is better than providing a component for that.

**Comment by SanEffect** [comment]
@MohamedRejeb @Efimj Thank you very much!

Btw, why not create a default toolbar?

**Comment by MohamedRejeb** [comment]
I'm planning to add a default toolbar, but it's not a priority for now.

**Comment by SanEffect** [comment]
Got it. Thanks again!
