### ISSUE TITLE
Add paragraph alignment support 

### ISSUE THREAD

**Issue by MohamedRejeb** [MohamedRejeb/Compose-Rich-Editor#19]
- Support paragraph alignment (left, right, center)
- Support aligning different paragraphs

**Comment by GabrielLasso** [comment]
I can implement this one

**Comment by GabrielLasso** [comment]
Can I implement this one?

**Comment by MohamedRejeb** [comment]
Yes, feel free to implement it. Here's some tips:
- Use the same approach as SpanStyle for ParagraphStyle.
- The start of a new paragraph will be after a line break

**Comment by MohamedRejeb** [comment]
Milestone 2 is done and v0.2.0 will be released tomorrow, I'm going to move this issue to Milestone 3

**Comment by GabrielLasso** [comment]
I won't be able to implement this... I am moving to a new apartment and dont have much free time, sorry...

**Comment by MohamedRejeb** [comment]
Ok no problem, good luck
