### ISSUE TITLE
Not able to run for ios

### ISSUE THREAD

**Issue by sunildhiman90** [MohamedRejeb/Compose-Rich-Editor#20]
Hi i added a build config for ios project using following config given in screen shot 
<img width="1512" alt="Screenshot 2023-05-09 at 12 36 10 PM" src="https://user-images.githubusercontent.com/35147222/237020218-c7c287d1-adb9-43e5-b86d-0bbcffe6b50e.png">

But i am not able to build, getting following error:
`** BUILD FAILED **

The following build commands failed:
	SwiftCompile normal arm64 Compiling\ ComposeViewControllerToSwiftUi.swift /Users/sunil/AndroidStudioProjects/Compose-Rich-Editor/sample/ios/Compose\ Rich\ Editor/ComposeViewControllerToSwiftUi.swift (in target 'Compose Rich Editor' from project 'Compose Rich Editor')
	SwiftCompile normal arm64 /Users/sunil/AndroidStudioProjects/Compose-Rich-Editor/sample/ios/Compose\ Rich\ Editor/ComposeViewControllerToSwiftUi.swift (in target 'Compose Rich Editor' from project 'Compose Rich Editor')
(2 failures)`

complete logs file:
[logs.docx](https://github.com/MohamedRejeb/Compose-Rich-Editor/files/11428320/logs.docx)

**Comment by MohamedRejeb** [comment]
It works fine for me with the KMM plugin, make sure to select the `.xcworkspace` file not the `.xcodeproj` file

**Comment by sunildhiman90** [comment]
Hi @MohamedRejeb , yes it worked fine for me with `.xcworkspace`, Thanx. kudos.
