### ISSUE TITLE
Reset to default font size when add a new line

### ISSUE THREAD

**Issue by cicoenote** [MohamedRejeb/compose-rich-editor#205]
Reset to default font size when add a new line.
The cursor will reset to default size, for example.

ABC       (20sp)
|             (The cursor will reset to 16sp)

And after add a charater, the new charater set to 20sp, and the cursor set to 20sp.
But when I delete this charater, the cursor will reset to 16sp, and type new charater will keep 16sp.

**Comment by MohamedRejeb** [comment]
Thanks for reporting this issue! I will check it.

**Comment by MohamedRejeb** [comment]
This should be fixed now, the only issue that you will encounter is that the cursor will reset to 16sp when the paragraph is empty which is an issue from Compose I will see how we can improve it, you can follow this issue for more informations #369.
