### ISSUE TITLE
Error while instantiating the RichText() in android compose.

### ISSUE THREAD

**Issue by Bala-0-1** [MohamedRejeb/Compose-Rich-Editor#206]
I'm getting this error when i try to use RichText(),

` Process: com.example.wellbee, PID: 9236
                                                                                                    java.lang.NoSuchMethodError: No virtual method getTextAlign-buA522U()Landroidx/compose/ui/text/style/TextAlign; in class Landroidx/compose/ui/text/ParagraphStyle; or its super classes (declaration of 'androidx.compose.ui.text.ParagraphStyle' appears in /data/app/com.example.wellbee-2/base.apk)
                                                                                                    	at com.mohamedrejeb.richeditor.parser.html.CssDecoder.decodeParagraphStyleToCssStyleMap$richeditor_compose_release(CssDecoder.kt:88)`

**Comment by MohamedRejeb** [comment]
Thanks for reporting this issue. Can you provide the html code that you tried to get this error?

**Comment by MohamedRejeb** [comment]
Please try the latest version `1.0.0-rc02` and let me know if you still have this issue.
