### ISSUE TITLE
Support <code> blocks

### ISSUE THREAD

**Issue by garretyoder** [MohamedRejeb/Compose-Rich-Editor#209]
For example the following string:
```
<code>
Example                   Text
Newline
</code>
```

Will render as:
`Example Text Newline`

Replacing all `\n` with `<p>` seems to reliably solve the newline problem, and replacing spaces with the html space code seems to solve that problem, but I'm unsure how to swap the font to monospace for that specific block of html. I think adding support for `<pre>` could also achieve the same effect, but it seems like the HTML import is discarding code tags - based on the readme I'd have expected it to support them?

**Comment by garretyoder** [comment]
I tested this in the web demo since the editor itself supports toggling code blocks, but it seems not to work. Initially I had it outputting a malformed code block that was: `>code`, but now I can't reproduce that - but I can reproduce the HTML output just not having code blocks at all.

**Comment by MohamedRejeb** [comment]
Thanks for reporting this,
I was thinking or using `code-span` tag for single line code and `code-block` tag for multi-line code (which is not implemented yet)
But you are right I think that it's better to use the correct html tags `code` and `pre`

For now multi-line code block is not supported yet

**Comment by garretyoder** [comment]
I assumed something like that, once #210 is merged I think you can close this specific issue as it covers code tags. However, I'm using your library to render some HTML comments in one of my projects and will need multiline support, so over the next couple weeks let me see if I can implement it and I'll submit a PR.

I'd just mimic how browsers do it, you have code blocks on their own newlines and then highlight until the longest line length.
