### ISSUE TITLE
Add link to current selection

### ISSUE THREAD

**Issue by kserocki** [MohamedRejeb/Compose-Rich-Editor#218]
Hey, is there a possibility to add the link to the current selection?

```
val state = RichTextState()
state.setText("Test THE LINK selection")
state.selection = TextRange(5, 13)
state.addLink("https://google.com/")
val output = state.toHtml()
```
Output should be `<p ...>Test <a href="https://google.com/" target="_blank">THE LINK</a> selection</p>`

Do you plan adding that feature?

**Comment by MohamedRejeb** [comment]
Hi,
For now it's not possible, but I see it's an important feature to have.
I'll try to add this in the next release.

**Comment by kserocki** [comment]
> I'll try to add this in the next release.

Do you have any timeline?

**Comment by MohamedRejeb** [comment]
Hopefully this week.

**Comment by kserocki** [comment]
Fingers crossed, I would really appreciate that feature!

**Comment by MohamedRejeb** [comment]
Check the docs the new link APIs: https://mohamedrejeb.github.io/Compose-Rich-Editor/links/
You can check the Slack demo as well: [here](https://github.com/MohamedRejeb/Compose-Rich-Editor/blob/main/sample/common/src/commonMain/kotlin/com/mohamedrejeb/richeditor/sample/common/slack/SlackDemoLinkDialog.kt)
