### ISSUE TITLE
Crash when setting maxLines

### ISSUE THREAD

**Issue by garretyoder** [MohamedRejeb/Compose-Rich-Editor#220]
When setting maxLines with some HTML text that contains paragraphs and a call to `getLineForOffset` is made, you'll get a crash with an index out of bounds exception from the function call.

Offending line (TextLayoutResultExt.kt):
```
val startLineNum = getLineForOffset(min(startOffset, endOffset))
val endLineNum = getLineForOffset(max(startOffset, endOffset))
```

This may be a platform bug since it's coming from the platform API.

**Comment by MohamedRejeb** [comment]
Thanks for reporting this issue.
I'll check it.

**Comment by MohamedRejeb** [comment]
I created an issue on issue tracker for this. Please vote with +1
I'm working on a workaround in the meantime.

https://issuetracker.google.com/issues/331844351
