### ISSUE TITLE
RichTextStateMarkdownParser.decode doesnt decode Lists or Highlighted text. 

### ISSUE THREAD

**Issue by IsrarShamim** [MohamedRejeb/compose-rich-editor#223]
When I use the `richTextState.toMarkdown()` which supposedly decodes the RichTextState to a markdown string  and returns String. 
It only decodes Bold, Italic, Code or Underline. It doesn't decode Lists. 
I really crave this feature, Because I want to store the text in Room and then also show it again when user reopens the note. but the problem is: when I store the text using `richTextState.toMarkdown()`  it only decodes certain values and not lists or highlighted lists. 
so when I reCompose the MarkDowned Text it does show text in bold or italic or underlined style. but it lacks the Lists and other very important styles.

Does this feature exist or it is coming or is it not  neccessary? 

this is my code:

- following code is where I save the text :
`changeNoteCardText = {
                                    changeNoteCardText(cardId.value,2,notesRichTextState.toMarkdown())
                                    notesRichTextState.setMarkdown(removeUnwantedSymbols( notesRichTextState.toMarkdown()))
                                    changeEdit(false)
                                }
                            )`
-and this is how I show the text: 
`LaunchedEffect(true) {
                                notesRichTextState.setMarkdown(removeUnwantedSymbols( notesText))
                            }`

**Comment by MohamedRejeb** [comment]
Thanks for reporting this!
Currently not all styles are supported in markdown but it's on top of my list.
You can use toHtml() instead and save the html string to Room, it support all the styles.

**Comment by IsrarShamim** [comment]
> Thanks for reporting this! Currently not all the styles are supported in markdown but it's on top of my list. You can use toHtml() instead and save the html string to Room, it supports all the styles.

Yes, I actually learned that when I was checking out the code. But the problem is my code is already heavily dependent on MarkDown that I can't use html now. 
I think I might have to do the transition regardless. it will be a pain but I will do it. 
Please add this feature for others at least.
Thank you❤️❤️

**Comment by IsrarShamim** [comment]
is there a function to convert markDown Text to Html string?

**Comment by MohamedRejeb** [comment]
Unfortunately no, all you can do is Convert Markdown -> RichTextState -> HTML

**Comment by MohamedRejeb** [comment]
Now lists should be working fine with markdown starting from `v1.0.0-rc04`

**Comment by MohamedRejeb** [comment]
Now Markdown supports lists and highlighted text with ``
