### ISSUE TITLE
 List Item Numbering Not Working

### ISSUE THREAD

**Issue by Shusek** [MohamedRejeb/Compose-Rich-Editor#234]
Description:
List items in  lack numbering.

Steps to Reproduce:

```
   val state = rememberRichTextState()
     val text =
         "<ol>  <li>test1</li> <li>test2</li></ol>   "
    state.setHtml(content)
    state.selection = TextRange.Zero
    RichTextEditor(
        state = state,
        readOnly = true,
    )
```

Expected Behavior:
List items should display sequential numbering.

Actual Behavior:
List items are numbered only with "1" number.

![Obraz 3 04 2024, godz  12 03](https://github.com/MohamedRejeb/Compose-Rich-Editor/assets/3973833/0f372f98-6f36-47ec-9bad-d9a76facbbaf)

**Comment by MohamedRejeb** [comment]
Thanks for reporting this issue. I will check it.
