### ISSUE TITLE
Crash after undoing

### ISSUE THREAD

**Issue by gogopro-dev** [MohamedRejeb/Compose-Rich-Editor#237]
## Crash after trying to undo deletion of the selected text via CTRL + Z.
- Compose-Rich-Editor version: **1.0.0-rc03**
- Compos Multiplatform version: **1.6.1**

https://github.com/MohamedRejeb/Compose-Rich-Editor/assets/81987829/27afad5f-a004-4e2a-bbba-cefe284aff43

Code of the test snippet:
```kotlin
@Composable
fun App() {
    val state = rememberRichTextState()
    RichTextEditor(
        state = state
    )
}
```

Steps to reproduce:

1. Type in any text
2. CTRL + A
3. Backspace
4. CTRL + Z

Looks pretty critical to me.

**Comment by MohamedRejeb** [comment]
Thanks for reporting this issue. I'll check it.
