### ISSUE TITLE
Toggle selected text style

### ISSUE THREAD

**Issue by GabrielLasso** [MohamedRejeb/Compose-Rich-Editor#24]
Is there a way to toggle the style of selected text?

Ex:
I type

foo bar

Then I select the `foo` and toggle the italic style, I expect it to become

 *foo* bar

**Comment by MohamedRejeb** [comment]
This is already implemented and it's coming in the next version

**Comment by MohamedRejeb** [comment]
#11

**Comment by GabrielLasso** [comment]
:clap: 
Nice

When the next version will come?

You can close this issue if you want

**Comment by MohamedRejeb** [comment]
It's coming soon in 2 or 3 days
