### ISSUE TITLE
Bullet list activation reset text style already applied 

### ISSUE THREAD

**Issue by RomainKB** [MohamedRejeb/compose-rich-editor#249]
Hello while testing the integration into our app, our QA raise a point which is tools reset with bullet list. 

Steps to reproduce:
- Select bold and/or italic tool
- Select bullet point
 
Actual: Previous tools are reseted 
Expected: Selected tools should be remains activated 

We expect that as style activation/deactivation doesn't change other configuration in other cases. More over if we have already have a word in bold and then activate/deactivate bullet list, the word while stay in bold and the style too.

**Comment by MohamedRejeb** [comment]
Hello,
Thanks for reporting this. I'll check it.

**Comment by MohamedRejeb** [comment]
This should be working fine now, feel free to reopen if you still encounter this issue.
