### ISSUE TITLE
When trying to toggle style on link - link disappears

### ISSUE THREAD

**Issue by kserocki** [MohamedRejeb/Compose-Rich-Editor#251]
Hey, first of all - great job on developing the lib! I have found one more bug - as in the title. Once you try to toggle bold/italic/underline on link, then the link disappears and is replaced by just styling. 
Please take a look at the video I made.

Version: v1.0.0-rc04

https://github.com/MohamedRejeb/Compose-Rich-Editor/assets/88652475/e3c96498-bd60-41e7-9aa6-e5b19212d294

**Comment by MohamedRejeb** [comment]
Hi,
Thanks for reporting this. I'll check it.
