### ISSUE TITLE
Lists indent

### ISSUE THREAD

**Issue by T8RIN** [MohamedRejeb/Compose-Rich-Editor#254]
How we can control this indents? I mean hardcoded 38.sp

![image](https://github.com/MohamedRejeb/Compose-Rich-Editor/assets/52178347/de22ed46-d245-4777-b512-387ebf7cf6a1)

**Comment by MohamedRejeb** [comment]
Hi,
This can't be controlled currently. I'm thinking of a good way to do this.

**Comment by T8RIN** [comment]
Maybe as param on rich text state?

**Comment by T8RIN** [comment]
Oh, i see, I will try to add if you don't plan to add it in the near future
