### ISSUE TITLE
How to highlight a different part of the text depending on the text and the current caret position?

### ISSUE THREAD

**Issue by Zomis** [MohamedRejeb/Compose-Rich-Editor#264]
I would like to accomplish some simple code-like highlighting (think about how IntelliJ IDEA / Android Studio highlights matching curly braces)

So for example, if I have this text: `|<1<2hello3>4>5` and my caret is at the position of `|`, I would like to highlight both the `<` between 1 and 2, and the `>` between 4 and 5. In order to accomplish this I need to be able to apply styles throughout the entire text, and not just at the selected position.

This seems impossible with the current API of the Compose Rich Editor. Will it ever be possible in the future?

Previously I used https://github.com/FXMisc/RichTextFX to do this when working with JavaFX, but now I want to accomplish the same thing in Compose.

**Comment by MohamedRejeb** [comment]
Hi,
Sorry for the late reply. Thanks for creating this issue.
This API is already available internally, I will see if it's possible to expose it.
