### ISSUE TITLE
Span style resets to default after deleting all characters

### ISSUE THREAD

**Issue by josmikulic** [MohamedRejeb/Compose-Rich-Editor#265]
This [#15](https://github.com/MohamedRejeb/Compose-Rich-Editor/issues/15) issue seems to be back

After I delete all characters in current paragraph style resets do default one and does not keep the one I used.

Version: 1.0.0-rc04

**Comment by MohamedRejeb** [comment]
I will publish a new release soon.
You will be able to control this behavior:
```kotlin
// Default is true
richTextState.config.preserveStyleOnEmptyLine = true
```
