### ISSUE TITLE
Add links support 

### ISSUE THREAD

**Issue by MohamedRejeb** [MohamedRejeb/Compose-Rich-Editor#27]
- Support links

**Comment by AzimMuradov** [comment]
If possible, I'd like to **change the pointer icon when hovering over a link**. I should also note that the current version of compose multiplatform doesn't change the pointer icon for buttons and other clickable objects by default. In contrast to this frustrating behavior, I'd like to be able to change the style of links on hover, as well as change the pointer icon to a "hand". I understand that the implementation of this behavior is quite difficult, but I think at least changing the icon would already be a major improvement.

**Comment by MohamedRejeb** [comment]
It would be great to have "hand" pointer on hovering links. I will try to release it in 0.3.0
