### ISSUE TITLE
Font size change (Increase or decrease)

### ISSUE THREAD

**Issue by mohsin-ali-brainx** [MohamedRejeb/Compose-Rich-Editor#274]
Is there a way to achieve changes in font sizes? Can we increase or decrease the font size of the text in editor ?

**Comment by MohamedRejeb** [comment]
Hi,
Yes you can do that using `addSpanStyle` method:
```kotlin
richTextState.addSpanStyle(SpanStyle(fontSize = 20.sp))
```

You can also change any other parameter in the `SpanStyle`
