### ISSUE TITLE
Add images support

### ISSUE THREAD

**Issue by MohamedRejeb** [MohamedRejeb/Compose-Rich-Editor#28]
- Add images support

**Comment by jxxfzgy** [comment]
Can you give me some ideas how to add images?

**Comment by MohamedRejeb** [comment]
For now it's not possible to display images in the rich editor, so as a start we are going to display images as string, similar to github editor for example:
![Screenshot 2023-06-05 at 5 13 42 PM](https://github.com/MohamedRejeb/Compose-Rich-Editor/assets/41842296/222141fa-834b-4f3f-b552-06718089b6d8)

Then in the Rich Text, which is just a representation without editing options we should see the image, the image is going to be passed and displayed as an `ImageBitmap` then we could implement on top of that painter resource or any other source of images like a url or whatever

**Comment by alirahimpour89** [comment]
I could be wrong and haven't tried it yet but shouldn't it be possible to show a image as inline content of the annotated string in TextFieldValue inside the TextField?  Or did you just mean that you won't support images on the textfield for now? 🙂

**Comment by MohamedRejeb** [comment]
Well AFAIK showing images as inline content of the annotated string is only possible with normal Text, because TextField doesn't support inline content. I had a conversation with a developer working the new compose text api and I told him about this limitation. So for know it's a limitation from Compose until they improve it or we found a workaround.

**Comment by alirahimpour89** [comment]
Okay weird that they use annotated string but doesn't support all of its features... Hope the new TextField APIs will support this later on, waiting for better support of keeping the TextField and cursor above the keyboard when the text is long when that one is released.

**Comment by dozy-programmer** [comment]
@MohamedRejeb Is this still in the works?

**Comment by ln-12** [comment]
Seems like a official Compose solution is still not in sight, see: https://issuetracker.google.com/issues/157506938

**Comment by MohamedRejeb** [comment]
Image support will be added to the `RichText` soon (Not the editor)
For the editor, we're still waiting for Compose to add inline element support in TextField.

**Comment by abnormalbbk** [comment]
> Image support will be added to the `RichText` soon (Not the editor) For the editor, we're still waiting for Compose to add inline element support in TextField.

@MohamedRejeb  Any update on this?

**Comment by vickyleu** [comment]
any progress

**Comment by MohamedRejeb** [comment]
This feature is almost there, hopefully it will be available in the next release after 1~2 weeks.

<img width="809" alt="Screenshot 2024-06-15 at 12 55 16 AM" src="https://github.com/MohamedRejeb/Compose-Rich-Editor/assets/41842296/5b940fdd-dde4-4ecb-aaa9-0dc5d237a3b0">
