### ISSUE TITLE
Why setConfig deprecated

### ISSUE THREAD

**Issue by T8RIN** [MohamedRejeb/Compose-Rich-Editor#281]
![image](https://github.com/MohamedRejeb/Compose-Rich-Editor/assets/52178347/773670f8-7055-4344-8983-814fc8a27f76)

**Comment by MohamedRejeb** [comment]
There's a new API available now, which is easier to use:
`richTextState.config.linkColor`

That message is wrong there, I should change it.

**Comment by MohamedRejeb** [comment]
Try the api above and feel free to reopen the issue if something goes wrong.
