### ISSUE TITLE
Built-in editor 

### ISSUE THREAD

**Issue by N7ghtm4r3** [MohamedRejeb/Compose-Rich-Editor#291]
Hi, there is a built-in editor like on Github to format the markdown text or it is maybe planned to be implemented? Thank you!

**Comment by MohamedRejeb** [comment]
Hi,
Yes, I'm planning to implement a markdown editor and an html editor. I can't give any ETA yet.

**Comment by N7ghtm4r3** [comment]
Thank you for the info and the reply!
