### ISSUE TITLE
-[MTLTextureDescriptorInternal validateWithDevice:]:1357: failed assertion `Texture Descriptor Validation MTLTextureDescriptor has height (>8192) greater than the maximum allowed size of 8192.

### ISSUE THREAD

**Issue by emirhanemmez** [MohamedRejeb/Compose-Rich-Editor#292]
I have a terms and conditions long html file. It crashes when I want to show on RichText. I think because of string size. It works fine on Android device. But ios is throwing this error:

-[MTLTextureDescriptorInternal validateWithDevice:]:1357: failed assertion `Texture Descriptor Validation
MTLTextureDescriptor has height (9444) greater than the maximum allowed size of 8192.

**Comment by MohamedRejeb** [comment]
Hi,
Can you split it into two `RichText` composables?

**Comment by emirhanemmez** [comment]
Hi, I did but it doesn't work .s

**Comment by MohamedRejeb** [comment]
You keep getting the same error?

**Comment by emirhanemmez** [comment]
Yep

**Comment by emirhanemmez** [comment]
This bug does not cause because of RichText. It's about Compose multiplatform framework. It works fine when you use in Column composable. But it does not work when you use in Dialog component. I'll open a bug to cmp for it. Great library work! @MohamedRejeb

**Comment by MohamedRejeb** [comment]
Thanks!
