### ISSUE TITLE
[BUG] Input fail when managing first line

### ISSUE THREAD

**Issue by kserocki** [MohamedRejeb/Compose-Rich-Editor#300]
There are probably other ways to reproduce it, but this one seem consistent. 

Steps:

1. Fill in input with a few lines and first line having some attribute set
2. Manually go back to the first line
3. Clear first line
4. Press any character

 

Expected:
- This character appears in a first line without any attributes

 

Actual:
- Character does not appear. Indicator jumps to the next line and highlights attributes from the next line.

Video:

https://github.com/MohamedRejeb/Compose-Rich-Editor/assets/88652475/ace05029-3c62-402e-b9e3-e28a6b6451a8

**Comment by MohamedRejeb** [comment]
Hi,
Thanks for opening this issue, I will check it.
