### ISSUE TITLE
Add supporting <h1> to <h6> Tags

### ISSUE THREAD

**Issue by GimazDo** [MohamedRejeb/compose-rich-editor#301]
At the moment I have only found support for inserting html code into richState. Is there any plan to support changing the current paragraph style?
Like
`
state.toggleParagraphStyle(
style = Header1
)
`

**Comment by MohamedRejeb** [comment]
Hi,
In Compose we have `SpanStyle` so you after parsing HTML, <h1> to <h6> tags are converted to `SpanStyle`.
Here's the `SpanStyle` for each tag, you can copy this code and use it in your project:
https://github.com/MohamedRejeb/Compose-Rich-Editor/blob/eccef2bcadebc6477059c8ddd3d0789fa6d667ea/richeditor-compose/src/commonMain/kotlin/com/mohamedrejeb/richeditor/parser/utils/ElementsSpanStyle.kt#L22 

```kotlin
internal val H1SpanStyle = SpanStyle(fontSize = 2.em, fontWeight = FontWeight.Bold)

state.toggleSpanStyle(H1SpanStyle)
```
