### ISSUE TITLE
Reset styling on multiple new line

### ISSUE THREAD

**Issue by thatsmanmeet** [MohamedRejeb/Compose-Rich-Editor#307]
If a user press enter/return key one time, then the styling currently active should remain active but on multiple enters (multiple new) lines, the styling should be disabled.  

@MohamedRejeb  Is there a way to achieve this right now? or do you have any plans to introduce this feature in future releases?

**Comment by MohamedRejeb** [comment]
Thanks for opening this issue, this an important improvement. Hopefully it will be added in the next release.
