### ISSUE TITLE
Is there a way to know which functionality is currently active?

### ISSUE THREAD

**Issue by thatsmanmeet** [MohamedRejeb/Compose-Rich-Editor#308]

**Comment by MohamedRejeb** [comment]
Hi,
Yes you can. Check the Slack demo sample from [here](https://github.com/MohamedRejeb/Compose-Rich-Editor/blob/main/sample/common/src/commonMain/kotlin/com/mohamedrejeb/richeditor/sample/common/slack/SlackDemoScreen.kt)

**Comment by thatsmanmeet** [comment]
Thanks a lot.
