### ISSUE TITLE
Issue with Numbered List Editing

### ISSUE THREAD

**Issue by Nikitosiki** [MohamedRejeb/compose-rich-editor#311]
I use [Shkiper](https://github.com/Efimj/Shkiper/), and I saw this problem in it, as I understand Shkiper uses your lib

Description:

There is a problem when creating and editing a numbered list in the text editor. When I create a numbered list with multiple items and edit any item except the last one, using the auto-fill feature from Google Cardboard, the word I select on the keyboard gets split into multiple items. Additionally, some letters might get lost completely.

Steps to Reproduce:

Open the text editor in the application.
Create a numbered list with multiple items.
Edit any item except the last one.
Use the auto-fill feature from Google Cardboard to complete a word.
Observe that the selected word gets split into multiple items and some letters may disappear.
Expected Behavior:
The selected word from Google Cardboard's auto-fill should be inserted correctly into the current list item without splitting into multiple items or losing letters.

Actual Behavior:
The selected word gets split into multiple list items and some letters may be lost.

Environment:

App Version: 1.9.0 ([Shkiper](https://github.com/Efimj/Shkiper/))
OS: Android 14 (PixelOS)
Device: Xiaomi Redmi Note 9s

Additional Information:

https://github.com/user-attachments/assets/933a72dc-db0b-4df0-9acf-b63969058977

**Comment by MohamedRejeb** [comment]
Hi,
Thanks for reporting this issue. I will check it.
