### ISSUE TITLE
The output markdown of underline span is incorrect

### ISSUE THREAD

**Issue by Goooler** [MohamedRejeb/Compose-Rich-Editor#314]
I'm using `com.mohamedrejeb.richeditor:richeditor-compose:1.0.0-rc05-k2`, you can repro this in #313.

**Comment by MohamedRejeb** [comment]
Thanks for reporting this, I will check it out.

**Comment by MohamedRejeb** [comment]
There's no underline in Markdown. So I added inline HTML tags support to Markdown and for this case we will use <u> HTML tag for underline.
