### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Onder7994** [MohamedRejeb/compose-rich-editor#327]
Hello.
I'm catching a strange bug on my physical device 
Model:  Xiaomi redmi note 11 PRO.
HyperOS OS, Android 13 TKQ1.221114.001.

In my app I am using your text library, sometimes when I try to move to a new line this error occurs. I couldn't catch it on emulator in android studio.
![photo_2024-08-16_23-08-55](https://github.com/user-attachments/assets/1935bb0d-5cb5-4df8-b54b-b9d422e401c1)

I use state like in README

`val richTextState = rememberRichTextState()`

Most often I catch this bug after loading data from the database and opening the edit screen. 
Before save formatted text I use 
`richTextState.toMarkdown()   (or toHtml, it doesn't matter)
After that I use richTextState.setMarkdown(htmlText)`

**Comment by MohamedRejeb** [comment]
Thanks for reporting this issue, I'm checking it.

**Comment by arjunmehtaa** [comment]
Please release this fix asap if possible thank you 🙏
