### ISSUE TITLE
Web Demo - Unable to Paste or Add Quotes

### ISSUE THREAD

**Issue by joelkanyi** [MohamedRejeb/compose-rich-editor#328]
I encountered issues while trying out the web demo. I’m unable to paste my HTML code for parsing. Additionally, when I attempted to type the code manually, I found that I couldn’t add quotes (").

https://github.com/user-attachments/assets/9852b63e-e2e0-4cc3-a7b9-c83f5a454bb7

**Comment by MohamedRejeb** [comment]
I updated the web demo, this should be fixed now.
> Note that images may not work on the web demo, I'm checking it.
