### ISSUE TITLE
Could not use $ sign in mark down RichTextState

### ISSUE THREAD

**Issue by NikitaLychkovski** [MohamedRejeb/compose-rich-editor#334]
If there is a $ sign anywhere in the string, it disappears from the RichText. For example: 

```
@Preview
@Composable
fun PreviewMarkDown() {
	Surface(
		color = Color.White,
	) {
		val state = rememberRichTextState()
		state.setMarkdown("This pizza cost $10")
		RichText(
			modifier = Modifier.padding(10.dp),
			state = state,
			style = Ref.text.bodyLarge,
			color = RockspoonTheme.colorScheme.onSurface
		)
	}
}
```
the resukt 
<img width="159" alt="image" src="https://github.com/user-attachments/assets/b6b79c54-3168-4c11-be9d-30a939376b7d">

 I tried to use "\$" or "\u0024" and got same result
<img width="139" alt="image" src="https://github.com/user-attachments/assets/22ff21a2-6f1f-4b2f-b8c9-7866a6124e6d">

But if I use "\\$" it would be 
<img width="141" alt="image" src="https://github.com/user-attachments/assets/b7ac47b2-d0fa-4e02-8c1d-ac22060d8734">

**Comment by MohamedRejeb** [comment]
Thanks for opening this issue. I will check it.
