### ISSUE TITLE
Show images on RichText without setting width and height

### ISSUE THREAD

**Issue by Philio** [MohamedRejeb/compose-rich-editor#336]
With a simple sample such as:

```kotlin
val richTextState = rememberRichTextState()
LaunchedEffect(html) {
    richTextState.setHtml(html)
}
RichText(
    state = richTextState,
    modifier = Modifier.fillMaxSize(),
    imageLoader = Coil3ImageLoader
)
```

The HTML is rendered, but images aren't loaded

**Comment by MohamedRejeb** [comment]
Hi,
Sorry for the late reply.
You need to setup coil on your project, check the sample:

https://github.com/MohamedRejeb/compose-rich-editor/blob/main/sample/common/src/commonMain/kotlin/com/mohamedrejeb/richeditor/sample/common/coil/ImageLoader.kt

https://github.com/MohamedRejeb/compose-rich-editor/blob/a507cec1bc3832c8b669541b46a71b0e979cf303/sample/common/src/commonMain/kotlin/com/mohamedrejeb/richeditor/sample/common/ui.theme/Theme.kt#L81

**Comment by Philio** [comment]
Hey, thanks for getting back to me

Coil has been working fine with the default image loader, but we've tried adding a custom one and the problem still persists

For example, the HTML returned from the API is:

```html
<p>A random image of some sheep...</p><p></p><p><img src="https://storage.googleapis.com/boxes-public-content-preview/0191a2bb-8415-7247-a562-df821cc73133-small"></p>
```

Coil is loading it...

```
💾 Successful (DISK) - https://storage.googleapis.com/boxes-public-content-preview/0191a2bb-8415-7247-a562-df821cc73133-small
```

But it's not being rendered:

![Screenshot_20240921_132535](https://github.com/user-attachments/assets/79ae4d2f-b3d7-4f27-8b75-a143f855e43d)

**Comment by MohamedRejeb** [comment]
Currently, only images with fixed width and height can be shown, something like this should work:
```html
<p>A random image of some sheep...</p><p></p><p><img src="https://storage.googleapis.com/boxes-public-content-preview/0191a2bb-8415-7247-a562-df821cc73133-small" width="100", height="100"></p>
```

I will work on getting the image's width and height by defaut.

**Comment by Philio** [comment]
Thanks! Will see if we can manipulate the HTML content in the backend to populate width/height and give it another try

**Comment by MohamedRejeb** [comment]
It will be available in the next release soon.

**Comment by MohamedRejeb** [comment]
Try the new version [v1.0.0-rc07](https://github.com/MohamedRejeb/compose-rich-editor/releases/tag/v1.0.0-rc07), it should be working fine now.

**Comment by Philio** [comment]
Works like a charm, thanks for sorting it!

![Screenshot_20240921_132535](https://github.com/user-attachments/assets/7830762d-af55-4ada-97fa-fd01717a6160)
