### ISSUE TITLE
Clicking urls in parsed html

### ISSUE THREAD

**Issue by ChristianSteffensen** [MohamedRejeb/compose-rich-editor#354]
When parsing html using state.setHtml(), it doesn't seem like using the UriHandler to listen to link click events works at all. Is this the expected behavior?

In this example, the onClick function is never called.

```
@Composable
fun WebViewText(
    html: String,
    modifier: Modifier = Modifier,
    onClick: (url: String) -> Unit = {},
) {
    val state = rememberRichTextState()
    state.setHtml(html)

    val uriHandler by remember {
        mutableStateOf(
            object : UriHandler {
                override fun openUri(uri: String) {
                    onClick(uri)
                }
            },
        )
    }

    CompositionLocalProvider(LocalUriHandler provides uriHandler) {
        BasicRichTextEditor(
            state = state,
            readOnly = true,
            enabled = false,
        )
    }
}
```

**Comment by MohamedRejeb** [comment]
Hi,
Clicking URLs is only working on `RichText`, not `RichTextEditor`.
When are in the editor, it doesn't make sense to open the link because the click should change the cursor position (like Slack for example).
You can know if the cursor is on a link or not, using `richTextState.isLink`:
```kotlin
LaunchedEffect(richTextState.isLink) {
    println("selectedLinkText: ${richTextState.selectedLinkText}")
    println("selectedLinkUrl: ${richTextState.selectedLinkUrl}")
}
```

**Comment by ChristianSteffensen** [comment]
> Hi,
> Clicking URLs is only working on `RichText`, not `RichTextEditor`.
> When you are in the editor, it doesn't make sense to open the link because the click should change the cursor position (like Slack for example).
> You can know if the cursor is on a link or not, using `richTextState.isLink`:
> ```kotlin
> LaunchedEffect(richTextState.isLink) {
>     println("selectedLinkText: ${richTextState.selectedLinkText}")
>     println("selectedLinkUrl: ${richTextState.selectedLinkUrl}")
> }
> ```

Ah thanks a lot! I wasn't aware there was a non-editor version of it. Works fine!
