### ISSUE TITLE
after RichTextState.setHtml, RichTextState.getHtml will append an additional <br>

### ISSUE THREAD

**Issue by XJianfei** [MohamedRejeb/compose-rich-editor#355]
After RichTextState.setHtml, if followed by <br>, the value returned by RichTextState.getHtml will have an additional <br> appended to the end.

`
val state = RichTextState()
state.setHtml("<p>ABC</p><br>")
state.getHtml()  // return  <p>ABC</p><br><br>
`
set `"<p>ABC</p><br>"`, but return `<p>ABC</p><br><br>`
This will cause an extra line.

1.0.0-rc05 is work fine, rc06 and rc07 both have this issure

**Comment by MohamedRejeb** [comment]
Thanks for reporting this issue, I will check it.
