### ISSUE TITLE
Adding newline toggles back removed span style

### ISSUE THREAD

**Issue by akishind-medlinx** [MohamedRejeb/compose-rich-editor#358]
Toggle bold/italic span style via `toggleSpanStyle`, add some text, remove the style (by calling `toggleSpanStyle` again with the same style), then add new line.

The style gets automatically toggled back again.

https://github.com/user-attachments/assets/2a27be4d-d5c1-4792-93d5-5f0b1e91fdae

**Comment by MohamedRejeb** [comment]
Hi,
Thanks for reporting this. I will check it.
