### ISSUE TITLE
Numbers in an ordered list jump to the left when starting editing

### ISSUE THREAD

**Issue by akishind-medlinx** [MohamedRejeb/compose-rich-editor#360]
Set some text, containing an ordered list, to the RichTextState via its `setMarkdown` method. If we then start editing, the numbers jump a little to the left - it looks like initially indents are set incorrectly.

https://github.com/user-attachments/assets/518f2d57-277e-4436-8add-9213f37ea86a

**Comment by MohamedRejeb** [comment]
Yes you are right, I will check it.
Indents are different in lists whether the line is the first line or not, and there are some adjustments to achieve this behavior.

<img width="131" alt="Screenshot 2024-09-27 at 8 55 21 AM" src="https://github.com/user-attachments/assets/3bbbe464-23c4-4a0d-bed5-f1bb44f76c67">
