### ISSUE TITLE
Bold-italic text is not recongnized when setting initial text

### ISSUE THREAD

**Issue by akishind-medlinx** [MohamedRejeb/compose-rich-editor#361]
Set some text, containing **_bold-italic_** text (text with three asterisks `***bold-italic***`) to `RichTextState.setMarkdown`.

The text is displayed as bold, without italic formatting.

https://github.com/user-attachments/assets/0e91e588-427a-4d9f-b9f7-8cd648238055

In the video I decode markdown text from the editor, then but the same markdown back.

**Comment by MohamedRejeb** [comment]
Thanks for all the issues that you are reporting. Your contribution will help me a lot to improve the library.

**Comment by MohamedRejeb** [comment]
I will release a new version today that will contain all the fixes.
