### ISSUE TITLE
Hi！I want to know how to listen if it is selected🤔🤔🤔🥲

### ISSUE THREAD

**Issue by ketd** [MohamedRejeb/compose-rich-editor#362]
Hi！I want to know how to listen if it is selected🤔🤔🤔🥲Thanks

**Comment by MohamedRejeb** [comment]
Hi,
Your question is not clear.
Please check slack sample: https://github.com/MohamedRejeb/compose-rich-editor/blob/main/sample/common/src/commonMain/kotlin/com/mohamedrejeb/richeditor/sample/common/slack/SlackDemoPanel.kt
