### ISSUE TITLE
Cursor moves to next line when text is added via suggestion 

### ISSUE THREAD

**Issue by ibraheemzulfiqar** [MohamedRejeb/compose-rich-editor#420]
Version: **v1.0.0-rc10**

When I add multiple lines and place the cursor at the end of a line, accepting a suggestion moves the cursor to the next line.
Only happens when `singleParagraph` is set to `false`.

https://github.com/user-attachments/assets/740bd114-3372-4f7a-b6de-27cbe9eb0c49

There's also an issue with the caret—it sometimes shows three. But I am not sure about the scenario.

https://github.com/user-attachments/assets/7034b745-d728-4659-9284-4bb680afecd8

**Comment by Ibraheemxd** [comment]
@MohamedRejeb

**Comment by Ibraheemxd** [comment]
@MohamedRejeb

**Comment by MohamedRejeb** [comment]
Hi,
Thanks for opening this issue. I'm working on it.

**Comment by ibraheemzulfiqar** [comment]
@MohamedRejeb any updates on this issue?

**Comment by MohamedRejeb** [comment]
The fix will be available in the next version
