### ISSUE TITLE
Crash when editing markdown that contains lots of code span backticks

### ISSUE THREAD

**Issue by Wavesonics** [MohamedRejeb/compose-rich-editor#444]
I don't exactly have a minimal repro case for this yet, And I've seen it with both even and odd numbers of backticks in the text. But it seems to be related to code spans cross paragraph boundaries... maybe.

I have a branch that reproduces the crash here: https://github.com/MohamedRejeb/compose-rich-editor/pull/442

**Comment by MohamedRejeb** [comment]
Thanks for reporting this, I'm checking it.
