### ISSUE TITLE
Migrate to `TextFieldState`

### ISSUE THREAD

**Issue by Wavesonics** [MohamedRejeb/compose-rich-editor#448]
`BasicTextField2` is fully released now as simply an overload of `BasicTextField` which accepts a `TextFieldState` object reather than a `TextFieldValue` object.

This is more suited to larger bodies of text, but also, it allows us access to scroll state, which unless I'm mistaken, is not available in the older `TextFieldValue` variant.

I was working on a branch that converts `BasicRichTextEditor` to use the `TextFieldState` variant under the hood, then it got me to wondering if that is what you would want @MohamedRejeb or should it be an additional variant? My thought was it should replace the `TextFieldValue`, it seems the compose team intends this to eventually replace theirs?

**Comment by j-hiertz** [comment]
@Wavesonics At the moment, I don’t think `BasicTextField2` and `TextFieldState` allow for styling text in the same way as `TextFieldValue` and `AnnotatedString`. Is this something you’ve managed to implement in your branch? Just curious to know.

**Comment by Wavesonics** [comment]
@j-hiertz damn, looking at it now I'm realizing it's not an option! Well thanks for pointing that at.

**Comment by Wavesonics** [comment]
Compose Multiplatform 1.9.0 is finally in beta with the `AnnotatedOutputTransformation` change.

I think it could work well with how this library already works under the hood, and could finally solve the remaining problems with custom drawing.

Plus we get the considerable performance benefits of BTF2's gap buffer implementation.

**Comment by ShadowRZ** [comment]
Me later found this issue and Compose 1.12 does add basic styling option to `TextFieldState`, see https://android-review.googlesource.com/c/platform/frameworks/support/+/4055100

Not sure about how this styling API compares with BTF though
