### ISSUE TITLE
Surface URI Click Callbacks for HTML Links

### ISSUE THREAD

**Issue by Kkotiswar** [MohamedRejeb/compose-rich-editor#471]
## Title: Surface URI Click Callbacks for HTML Links

**Problem:**

*   `RichText` currently opens HTML links directly in the browser.
*   No callback for intercepting link clicks for tracking or custom behavior.

**Requirement:**

*   Introduce `onUriClick` callback to `RichText`.
*   Callback should pass the clicked URL string.
*   Default behavior (open in browser) if `onUriClick` is not provided.
*   Callback returns `Boolean` which decides whether to open URI or not.

**Benefits:**

*   Enable tracking link clicks.
*   Allow custom navigation logic.
*   Maintain default behavior.
*   Increased flexibility for developer.
*   Backward compatible

**Code Location:**

*   Modify `BasicRichText` or `RichText` where `detectTapGestures` handles link clicks.

**Comment by MohamedRejeb** [comment]
Thanks for opening this issue. Actually, it's possible to intercept Uri clicks, it's not straightforward though.

It's listed in the documentation: https://mohamedrejeb.github.io/compose-rich-editor/links/#add-links

```kotlin
val myUriHandler = remember {
    object : UriHandler {
        override fun openUri(uri: String) {
            // Link clicked
        }
    }
}

CompositionLocalProvider(
    LocalUriHandler provides myUriHandler,
) {
    RichText()
}
```

**Comment by Kkotiswar** [comment]
@MohamedRejeb thanks for the info, I saw one more issue where this library is not able to render the text that is currently in between <html> tags
i.e  `<html> some text </html>` displays nothing

**Comment by MohamedRejeb** [comment]
Currently, I'm skipping anything outside `<body>` tag. I've created a new issue for that #479
