### ISSUE TITLE
The Unordered List Functionality Doesn't work

### ISSUE THREAD

**Issue by DAKSHSEMWAL** [MohamedRejeb/Compose-Rich-Editor#49]
<img width="1431" alt="image" src="https://github.com/MohamedRejeb/Compose-Rich-Editor/assets/14074454/5a16c780-713c-4328-aeff-669b926d7741">

**Comment by MohamedRejeb** [comment]
It's not compatible with HTML import/export for now, the existing code for unordered list is not scalable at all, I'm going to reimplement this feature from scratch.

**Comment by MohamedRejeb** [comment]
Check out the latest version
