### ISSUE TITLE
Allow storing Editor Value State somewhere else

### ISSUE THREAD

**Issue by wakaztahir** [MohamedRejeb/Compose-Rich-Editor#68]
rememberRichTextState() can only be called inside a compose context

We should be able to do something like this

val value = RichTextEditorValue() // this doesn't need to be remembered
val state = rememberRichTextState(myValue)

I know something like this exists in the previous deprecated API but I am talking about current implementation that supports paragraph , Since idea of separating the core is already there , This could be part of core. Which should be done when the implementation of editor is done

**Comment by MohamedRejeb** [comment]
You can create rich text state without `rememberRichTextState`, directly using the constructor `RichTextState()`
