### ISSUE TITLE
Problem with text selection. 

### ISSUE THREAD

**Issue by sayler666** [MohamedRejeb/Compose-Rich-Editor#76]
When using RichTextEditor and trying to select text there is a lag and issues with the precision of selection. 
The issue is especially noticeable when after selecting a single word by long press, I try to extend or contract the selection by dragging selection handles. Sometimes I can't move the handles at all.

[Example](https://1drv.ms/v/s!AsR8ea2FCT0ShYJA0_4ig2Tt88S8fA )

**Comment by MohamedRejeb** [comment]
Thanks for reporting this issue, I will check this.

**Comment by MohamedRejeb** [comment]
I'll try to publish a new release today containing the fix.
