### ISSUE TITLE
RichTextState.setHtml() not working on release build (isDebuggable = false)

### ISSUE THREAD

**Issue by sayler666** [MohamedRejeb/Compose-Rich-Editor#82]
There is a problem with the `RichTextState.setHtml()` method on non-debuggable builds. 
No text is visible in `RichText` or `BasicRichTextEditor` when I use this method. 
`setText()` is working correctly in the same type of build. 

In builds with `isDebuggable = true` everything is working fine.

Sample code:
```
val html = "<p><b>Compose Rich Editor</b></p>"
val richTextState = rememberRichTextState()
richTextState.setHtml(html)

RichText(state = richTextState)
```

**Comment by MohamedRejeb** [comment]
Thanks for reporting, I'll check this issue.

**Comment by MohamedRejeb** [comment]
Try again with the new version and let me know if it works now: `1.0.0-beta02`
