### ISSUE TITLE
Crash when I try set paragraph more then 2

### ISSUE THREAD

**Issue by v1rus-dev** [MohamedRejeb/Compose-Rich-Editor#86]
When I launch RichEditor without text, and press Enter 3 time, I get a crash.

<img width="316" alt="Снимок экрана 2023-08-04 в 08 59 31" src="https://github.com/MohamedRejeb/Compose-Rich-Editor/assets/72551198/4e514cda-93ae-4809-b287-1ecfa4016d91">

**Comment by v1rus-dev** [comment]
Crash on the 670 line in RichTextState.
java.lang.StringIndexOutOfBoundsException: begin 0, end 1, length 0

**Comment by MohamedRejeb** [comment]
Thanks for reporting this issue, it's similar to this one #83 I will publish a new release with the fixes in a few days

**Comment by jjrodcast** [comment]
@MohamedRejeb I'm having the same issue, any idea when it will be fixed?

**Comment by MohamedRejeb** [comment]
a new release is going to be published today containing the fix!
