### ISSUE TITLE
Migrate to kotlin 1.9.0 and compose 1.5.0

### ISSUE THREAD

**Issue by MohamedRejeb** [MohamedRejeb/Compose-Rich-Editor#93]
**Ksoup** needs to be updated to `0.2.0` which is compatible with Kotlin `1.9.0`

**Comment by alialbaali** [comment]
Thanks for creating this awesome library!

Any update on this?

**Comment by MohamedRejeb** [comment]
I'll try to update compose to 1.5.0 ASAP, maybe later this week.
