### ISSUE TITLE
A  way to get notified when currentParagraphStyle and currentSpanStyle change

### ISSUE THREAD

**Issue by janseeger** [MohamedRejeb/Compose-Rich-Editor#99]
Currently one can read the current value of those properties but there's no way to get notified when the property has changed.

I have [experimented with converting the properties to derived states](https://github.com/janseeger/Compose-Rich-Editor/commit/bf814d2ce6448eaf8b6a6a57a2c12e38d5ebd460), but I'm not sure this can be done without exposing the state and breaking API compatibility.

**Comment by MohamedRejeb** [comment]
Sorry for the late reply.
Add the `currentParagraphStyle` or `currentSpanStyle` as key to the `LaunchedEffect` and you will get notified when it's changed.
```
LaunchedEffect(richTextState.currentSpanStyle) {
    // do something with the new state.
}
```
